{"level":"error","message":"Error: User already has an account\n    at AppUserSignUpUsecase.<anonymous> (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:18:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:5:58)","timestamp":"27/02/2024 12:06:41"}
{"level":"error","message":"Error: User already has an account\n    at AppUserSignUpUsecase.<anonymous> (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:18:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:5:58)","timestamp":"27/02/2024 12:06:58"}
{"level":"error","message":"Error: Document 2 already registered\n    at AppUserSignUpUsecase.<anonymous> (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:23:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:5:58)","timestamp":"27/02/2024 12:07:27"}
{"level":"error","message":"Error: Email is already in use\n    at AppUserSignUpUsecase.<anonymous> (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:71:70)\n    at Generator.next (<anonymous>)\n    at fulfilled (C:\\Users\\james\\Documents\\4.Projetos\\16.correct-nodejs-backend\\src\\modules\\AppUser\\AppUserSignUp\\usecases\\app-user.signup.usecase.ts:5:58)","timestamp":"27/02/2024 12:08:47"}
